= Fault Tolerance Core

include::partial$internals.adoc[]

The core idea in {smallrye-fault-tolerance} is a `FaultToleranceStrategy`.
It is an interface that looks like this:

[source,java]
----
interface FaultToleranceStrategy<V> {
    Future<V> apply(FaultToleranceContext<V> ctx);
}
----

NOTE: The `Future` type here is _not_ a `java.util.concurrent.Future`.
It comes from {smallrye-fault-tolerance} and it could be described as a very bare-bones variant of `CompletableFuture`, except it's split into `Completer` and `Future`.
It is not supposed to be used outside of this project.

The `FaultToleranceContext` is a `Supplier<Future<V>>` that represents the method invocation guarded by this fault tolerance strategy.
The fault tolerance strategy does its work around `ctx.get()`.
It can catch exceptions, invoke `ctx.get()` multiple times, invoke something else, etc.
As an example, let's consider this strategy, applicable to methods that return a `String`:

[source,java]
----
public class MyStringFallback implements FaultToleranceStrategy<String> {
    @Override
    public Future<String> apply(FaultToleranceContext<String> ctx) {
        Completer<String> completer = Completer.create();
        try {
            ctx.get().then((value, error) -> {
                if (error == null) {
                    completer.complete(value);
                } else {
                    completer.complete("my string value");
                }
            });
        } catch (Exception ignored) {
            completer.complete("my string value");
        }
        return completer.future();
    }
}
----

This is a very simple fallback mechanism, which returns a pre-defined value in case of an exception.

In the {smallrye-fault-tolerance} codebase, you can find implementations of all the strategies required by {microprofile-fault-tolerance}: retry, fallback, timeout, circuit breaker or bulkhead.
Asynchronous invocation, delegated to a thread pool, is of course also supported.

When multiple fault tolerance strategies are supposed to be used to guard one method, they form a chain.
Continuing with our simple example, adding the ability to chain with another strategy would look like this:

[source,java]
----
public class MyStringFallback implements FaultToleranceStrategy<String> {
    private final FaultToleranceStrategy<String> delegate;

    public MyStringFallback(FaultToleranceStrategy<String> delegate) {
        this.delegate = delegate;
    }

    @Override
    public Future<String> apply(FaultToleranceContext<String> ctx) {
        Completer<String> completer = Completer.create();
        try {
            delegate.apply(ctx).then((value, error) -> {
                if (error == null) {
                    completer.complete(value);
                } else {
                    completer.complete("my string value");
                }
            });
        } catch (Exception ignored) {
            completer.complete("my string value");
        }
        return completer.future();
    }
}
----

We see that one strategy delegates to another, passing the `FaultToleranceContext` along.
In fact, all the implementations in {smallrye-fault-tolerance} are written like this: they expect to be used in a chain, so they take another `FaultToleranceStrategy` to which they delegate.
But if all strategies have this form, when is `ctx.get()` actually invoked?
Good question!
The ultimate `ctx.get()` invocation is done by a special fault tolerance strategy which is called, well, `Invocation`.

As an example which uses real {microprofile-fault-tolerance} annotations, let's consider this method:

[source,java]
----
@Retry(...)
@Timeout(...)
@Fallback(...)
public void doSomething() {
    ...
}
----

The chain of fault tolerance strategies will look roughly like this:

[source]
----
Fallback(
    Retry(
        Timeout(
            Invocation(
                // ctx.get() will happen here
                // that will, in turn, invoke doSomething()
            )
        )
    )
)
----

The order in which the strategies are chained (or, in fact, nested) is specified by {microprofile-fault-tolerance}.

Other strategies might also be present in more complex cases.
For example, if metrics are enabled, a special strategy is used that collects metrics.
If the method is `@Asynchronous`, a special strategy is used that offloads method execution to another thread.
Etc.
