= Project Structure

* `api`:  {smallrye-fault-tolerance} API, additional to the {microprofile-fault-tolerance} API.
  Treated as a public API.
* `implementation/core`: Implementation of core fault tolerance strategies.
  Independent of the {microprofile-fault-tolerance} API or the {smallrye-fault-tolerance} API.
   Treated as private API, no compatibility guaranteed.
* `implementation/fault-tolerance`: Implementation of the {microprofile-fault-tolerance} API and the {smallrye-fault-tolerance} API.
  Based on CDI and the `core` module.
* `implementation/context-propagation`: Optional integration with MicroProfile Context Propagation.
  See xref:integration/context-propagation.adoc[Context Propagation integration].
* `implementation/tracing-propagation`: Optional integration between MicroProfile Context Propagation and OpenTracing.
  See xref:integration/opentracing.adoc[OpenTracing integration].
* `testsuite/basic`: Basic test suite.
  Some parts of it overlap with the Eclipse MicroProfile Fault Tolerance TCK.
* `testsuite/integration`: Context Propagation integration test suite.
* `testsuite/tck`: Runs the implementation against the Eclipse MicroProfile Fault Tolerance TCK.
* `doc`: This documentation.
