= Project Structure

* `api`:  {smallrye-fault-tolerance} API, additional to the {microprofile-fault-tolerance} API.
  Treated as a public API.
* `implementation/core`: Implementation of core fault tolerance strategies.
  Independent of the {microprofile-fault-tolerance} API or the {smallrye-fault-tolerance} API.
   Treated as private API, no compatibility guaranteed.
* `implementation/fault-tolerance`: Implementation of the {microprofile-fault-tolerance} API and the {smallrye-fault-tolerance} API.
  Based on CDI and the `core` module.
  The configuration system is based on the `autoconfig` module.
* `implementation/autoconfig/core`: Core classes of the {smallrye-fault-tolerance} configuration system.
  Required at runtime.
* `implementation/autoconfig/processor`: An annotation processor that generates implementations of config interfaces.
  Only required during {smallrye-fault-tolerance} build.
* `implementation/context-propagation`: Optional integration with MicroProfile Context Propagation.
  See xref:integration/context-propagation.adoc[Context Propagation integration].
* `implementation/tracing-propagation`: Optional integration between MicroProfile Context Propagation and OpenTracing.
  See xref:integration/opentracing.adoc[OpenTracing integration].
* `implementation/vertx`: Optional integration of the Vert.x event loop.
  See xref:integration/event-loop.adoc[event loop integration].
* `testsuite/basic`: Basic test suite.
  Some parts of it overlap with the Eclipse MicroProfile Fault Tolerance TCK.
* `testsuite/integration`: Integration test suite.
  Includes several Context Propagation and Vert.x tests.
* `testsuite/tck`: Runs the implementation against the Eclipse MicroProfile Fault Tolerance TCK.
* `doc`: This documentation.
