:microprofile-fault-tolerance: https://github.com/eclipse/microprofile-fault-tolerance/
:ci: https://github.com/smallrye/smallrye-fault-tolerance/actions?query=workflow%3A%22SmallRye+Build%22
:sonar: https://sonarcloud.io/dashboard?id=smallrye_smallrye-fault-tolerance

image:https://github.com/smallrye/smallrye-fault-tolerance/workflows/SmallRye%20Build/badge.svg?branch=master[link={ci}]
image:https://sonarcloud.io/api/project_badges/measure?project=smallrye_smallrye-fault-tolerance&metric=alert_status["Quality Gate Status", link={sonar}]
image:https://img.shields.io/github/license/smallrye/smallrye-fault-tolerance.svg["License", link="http://www.apache.org/licenses/LICENSE-2.0"]
image:https://img.shields.io/maven-central/v/io.smallrye/smallrye-fault-tolerance?color=green[]

== SmallRye Fault Tolerance

SmallRye Fault Tolerance is an implementation of {microprofile-fault-tolerance}[Eclipse MicroProfile Fault Tolerance].

=== Integration

==== Thread pools
A vendor may want to provide custom executor services for the fault tolerant executions.
This can be achieved by creating a custom `io.smallrye.faulttolerance.ExecutorFactory` and
registering it via `ServiceLoader`.

If multiple factories are discovered, the one with the *highest* priority is used.

==== Context Propagation
`smallrye-fault-tolerance-context-propagation` provides an integration with MicroProfile Context Propagation.
It is done by providing a custom `ExecutorFactory`, namely `ContextPropagationExecutorFactory`.

Please note that if you override the executor factory with a custom one and would like the context propagation
to be enabled, you have to make sure your executor factory creates the executor services in the right way.

==== Open Tracing
SmallRye Fault Tolerance enables trace propagation to the asynchronous invocations via MicroProfile
Context Propagation. To enable it, add `smallrye-fault-tolerance-tracing-propagation` to your project

=== Configuration
SmallRye Fault Tolerance supports all the configuration options of MicroProfile Fault Tolerance
and, additionally, the following options:

- `io.smallrye.faulttolerance.globalThreadPoolSize`, the amount of threads used by the fault
tolerance mechanisms. This does not include bulkhead thread pools. Defaults to `100`
- `io.smallrye.faulttolerance.timeoutExecutorThreads`, the size of the thread pool used for scheduling timeouts.
Defaults to `5`

=== Instructions

Compile and install this project:
[source,bash]
----
mvn clean install
----

==== Project structure

* link:implementation[] - Implementation of the Eclipse MicroProfile Fault Tolerance API.
* link:tck[] - Test suite to run the implementation against the Eclipse MicroProfile Fault Tolerance TCK.
* link:docs[] - Project documentation.

==== Links

* http://github.com/smallrye/smallrye-fault-tolerance/[Project Homepage]
* {microprofile-fault-tolerance}[Eclipse MicroProfile Fault Tolerance]

