= Event Loop

{smallrye-fault-tolerance} provides an API to integrate with event loops used in non-blocking runtimes.

WARNING: This integration API comes from the `core` module and so is treated as private.
If you intend to implement it, please let us know in the {smallrye-fault-tolerance} issue tracker.
We'd prefer all the implementations to live in the {smallrye-fault-tolerance} project.

The integrator must implement the `EventLoop` interface, which lets {smallrye-fault-tolerance} schedule execution of ``Runnable``s to a later turn of an event loop.
Implementations are discovered through `ServiceLoader`, so the corresponding `META-INF/services/\...` file must also exist.

At most one implementation of `EventLoop` may be present at runtime.
{smallrye-fault-tolerance} will use it to:

- execute retry attempts on the original thread, if the guarded method is `@NonBlocking` and is called on an event loop thread.

If no event loop integration is present, the tasks described above will be offloaded to the xref:integration/thread-pool.adoc[thread pool].

== Vert.x

{smallrye-fault-tolerance} includes an implementation of the event loop integration API for Vert.x.
This implementation is compiled and tested against Vert.x version 4.0, but should also work fine with Vert.x 3.x.

This implementation is present in the `io.smallrye:smallrye-fault-tolerance-vertx` artifact.
Including this artifact is enough to enable the Vert.x integration.

NOTE: The Vert.x implementation is treated as public, but only as described here.
That is, the artifact should be treated as opaque, no guarantees about its internals are made.
