= Programmatic API Integration Concerns

This page describes integration concerns of the xref:reference/programmatic-api.adoc[Programmatic API] of {smallrye-fault-tolerance}.

== CDI Implementation

The CDI implementation will use the thread pool an integrator provides (see xref:integration/thread-pool.adoc[Thread Pool]).
This also extends to the context propagation integration (see xref:integration/context-propagation.adoc[Context Propagation]).

It will also use the event loop support, if integrator provides one (see xref:integration/event-loop.adoc[Event Loop]).

In other words, runtimes that use the CDI implementation don't have to do any extra integration work.
The existing integration is enough.

== Standalone Implementation

The standalone implementation exposes a single integration point: the `StandaloneFaultTolerance.configure()` static method.
This method must be called before fault tolerance is first used.
It accepts a custom implementation of the `Configuration` interface, which allows customizing:

* `enabled()`: if `false`, all fault tolerance strategies except fallback and thread offload are disabled
* `executor()`: executor for thread offloads and other asynchronous tasks

When no `Configuration` is provided, sensible defaults are used:

* fault tolerance is enabled unless system property `MP_Fault_Tolerance_NonFallback_Enabled` is set to `false`
* a thread pool obtained using `Executors.newCachedThreadPool()` is used as an executor

Users of the standalone implementation that also use an event loop based library, such as Vert.x, may integrate the event loop support as described in xref:integration/event-loop.adoc[Event Loop].

=== Lifecycle

The thread pool and all other internal resources are initialized lazily, on the first use.
The `StandaloneFaultTolerance.shutdown()` method may be used on application shutdown to shut down these internal resources.

The executor is only shut down when no `Configuration` was provided and {smallrye-fault-tolerance} had to create an executor on its own.
If `Configuration` was provided, the executor shutdown is left to the integrator; it is _not_ attempted automatically.

At the end of `StandaloneFaultTolerance.shutdown()`, the `Configuration.onShutdown()` method is called.

After `StandaloneFaultTolerance.shutdown()`, it is not possible to reinitialize {smallrye-fault-tolerance} again.
